-- Smart Me Asset Tracker — Seed Data
-- Run AFTER schema.sql
-- Creates 2 users and seeds User 1's growth portfolio.
-- Replace PIN hashes with real values generated by the app on first login setup.

-- ============================================================
-- USERS
-- ============================================================
-- Placeholder PIN hashes. The app will overwrite these when users set their PINs.
-- Format: SHA-256(pin + salt) stored as hex string.

INSERT INTO users (id, name, pin_hash, salt, telegram_chat_id) VALUES
  ('00000000-0000-0000-0000-000000000001', 'User1', 'REPLACE_WITH_HASH', 'REPLACE_WITH_SALT', '7639152790'),
  ('00000000-0000-0000-0000-000000000002', 'User2', 'REPLACE_WITH_HASH', 'REPLACE_WITH_SALT', '8450768699')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- USER 1 — GROWTH PORTFOLIO
-- ============================================================

INSERT INTO portfolios (id, user_id, name, type, dca_budget_usd) VALUES
  ('10000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', 'Growth', 'growth', 310.00)
ON CONFLICT (id) DO NOTHING;

-- Holdings: target_pct set, shares/avg_cost start at 0 (user fills in actuals)
-- Targets sum to 94% — 6% is unallocated (more tickers to be added later)
INSERT INTO holdings (portfolio_id, ticker, target_pct, shares, avg_cost_usd) VALUES
  ('10000000-0000-0000-0000-000000000001', 'GOOGL',  20.00, 0, 0),
  ('10000000-0000-0000-0000-000000000001', 'NVDA',   15.00, 0, 0),
  ('10000000-0000-0000-0000-000000000001', 'AMZN',   12.00, 0, 0),
  ('10000000-0000-0000-0000-000000000001', 'LLY',     9.00, 0, 0),
  ('10000000-0000-0000-0000-000000000001', 'AAPL',    8.00, 0, 0),
  ('10000000-0000-0000-0000-000000000001', 'NFLX',    8.00, 0, 0),
  ('10000000-0000-0000-0000-000000000001', 'COST',    7.00, 0, 0),
  ('10000000-0000-0000-0000-000000000001', 'RKLB',    6.00, 0, 0),
  ('10000000-0000-0000-0000-000000000001', 'BKNG',    6.00, 0, 0),
  ('10000000-0000-0000-0000-000000000001', 'TSM',     3.00, 0, 0)
ON CONFLICT (portfolio_id, ticker) DO NOTHING;

-- ============================================================
-- INITIAL EXCHANGE RATE PLACEHOLDER
-- GAS DataAgent will overwrite this daily with live USD/THB rate
-- ============================================================

INSERT INTO exchange_rates (from_currency, to_currency, rate, date) VALUES
  ('USD', 'THB', 33.50, CURRENT_DATE)
ON CONFLICT (from_currency, to_currency, date) DO NOTHING;
