export const THAI_BANKS = {
  KBANK:    { name: 'กสิกรไทย',              nameEN: 'Kasikorn Bank',            logo: '/assets/banks/KBANK.png',    color: '#138f2d' },
  SCB:      { name: 'ไทยพาณิชย์',            nameEN: 'SCB',                      logo: '/assets/banks/SCB.png',      color: '#4e2d8c' },
  BBL:      { name: 'กรุงเทพ',               nameEN: 'Bangkok Bank',             logo: '/assets/banks/BBL.png',      color: '#1b3f7a' },
  KTB:      { name: 'กรุงไทย',              nameEN: 'Krungthai Bank',            logo: '/assets/banks/KTB.png',      color: '#009FDA' },
  BAY:      { name: 'กรุงศรีอยุธยา',         nameEN: 'Krungsri Bank',            logo: '/assets/banks/BAY.png',      color: '#FFC300' },
  TTB:      { name: 'ทีเอ็มบีธนชาต',         nameEN: 'TMBThanachart Bank',       logo: '/assets/banks/TTB.png',      color: '#002B6C' },
  GSB:      { name: 'ออมสิน',               nameEN: 'Government Savings Bank',  logo: '/assets/banks/GSB.png',      color: '#eb198d' },
  BAAC:     { name: 'ธ.ก.ส.',               nameEN: 'BAAC',                     logo: '/assets/banks/BAAC.png',     color: '#4CAF50' },
  UOB:      { name: 'ยูโอบี',               nameEN: 'UOB',                      logo: '/assets/banks/UOB.png',      color: '#0f3d8c' },
  CIMB:     { name: 'ซีไอเอ็มบี',           nameEN: 'CIMB Thai',                logo: '/assets/banks/CIMB.png',     color: '#e2001a' },
  KKP:      { name: 'เกียรตินาคินภัทร',      nameEN: 'Kiatnakin Phatra Bank',    logo: '/assets/banks/KKP.png',      color: '#003087' },
  TISCO:    { name: 'ทิสโก้',               nameEN: 'Tisco Bank',               logo: '/assets/banks/TISCO.png',    color: '#004B9A' },
  LHB:      { name: 'แลนด์ แอนด์ เฮ้าส์',  nameEN: 'LH Bank',                  logo: '/assets/banks/LHB.png',      color: '#004B87' },
  TCRB:     { name: 'ไทยเครดิต',            nameEN: 'Thai Credit Bank',         logo: '/assets/banks/TCRB.png',     color: '#1a5276' },
  GHB:      { name: 'ธ.อ.ส.',              nameEN: 'GH Bank',                  logo: '/assets/banks/GHB.png',      color: '#f37021' },
  IBANK:    { name: 'อิสลามแห่งประเทศไทย',  nameEN: 'Islamic Bank of Thailand', logo: '/assets/banks/IBANK.png',    color: '#005f38' },
  CITI:     { name: 'ซิตี้แบงก์',           nameEN: 'Citibank',                 logo: '/assets/banks/CITI.png',     color: '#003B70' },
  HSBC:     { name: 'เอชเอสบีซี',           nameEN: 'HSBC',                     logo: '/assets/banks/HSBC.png',     color: '#DB0011' },
  ICBC:     { name: 'ไอซีบีซี',             nameEN: 'ICBC',                     logo: '/assets/banks/ICBC.png',     color: '#C0392B' },
  TrueMoney: { name: 'ทรูมันนี่',           nameEN: 'True Money',               logo: '/assets/banks/TrueMoney.png',color: '#ff6600' },
  PromptPay: { name: 'พร้อมเพย์',           nameEN: 'PromptPay',                logo: '/assets/banks/PromptPay.png',color: '#2563eb' },
};
